---
pipeline:
  inputs:
    - name: dummy
      dummy: 'foo'
      interval_sec: 1

  outputs:
    - name: 'opentelemetry'
      match: '*'
      host: 'otelcol'
      port: 4318
      tls: false
      logs_uri: /v1/logs
