---
pipeline:
  inputs:
    - name: dummy
      dummy: '{"misclabel": "dummy", "message": "dummy log entry here" }'
      interval_sec: 1

      processors:
        logs:
          - name: opentelemetry_envelope

  outputs:
    - name: 'opentelemetry'
      match: '*'
      host: 'otelcol'
      port: 4318
      tls: false
      logs_uri: /v1/logs
      logs_body_key_attributes: true
